import Link from "next/link";

export const metadata = {
  title: "Belajar next",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ul>
          <li>
            <Link href="/">Home</Link>
            <br />
            <Link href="/dashboard">Dashboard</Link>
            <br />
            <Link href="/settings">Settings</Link>
            <br />
            <Link href="/calculator">Calculator</Link>
            <br />
            <Link href="/cari">Cari</Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
